### ISSUE TITLE
Use FeatureSummary for cmake configuration

### ISSUE THREAD

**Issue by lbeltrame** [g-fb/haruna#1]
`FeatureSummary` is a neat module in CMake (https://cmake.org/cmake/help/latest/module/FeatureSummary.html) which is very useful to check for required and optional dependencies and have the configuration step output at the end what's present and what's missing.

It's very useful for packagers because it gives a nice list of everything as opposed to failing for every `find_package` calls.

**Comment by g-fb** [comment]
Done https://github.com/g-fb/haruna/commit/3976f16f70ec69f0c0285e3c394fb4930a325cb6

**Comment by lbeltrame** [comment]
Thanks. However, it needs an adjustment to work properly. You will need:

```
find_package(Foobar)
set_package_properties(Foobar TYPE REQUIRED) 
```

for each package.

**Comment by g-fb** [comment]
Added `find_package` and `set_package_properties` for each dependency https://github.com/g-fb/haruna/commit/2743c0698bc13b86c385e6ee5a279fe94608132b
