### ISSUE TITLE
haruna 0.2.1 build fails with qt 5.12.7

### ISSUE THREAD

**Issue by lgbaldoni** [g-fb/haruna#16]
Using openSUSE Leap 15.2, the build fails like [this](https://github.com/g-fb/haruna/files/5380653/haruna-qt5127.txt).

**Comment by g-fb** [comment]
I know, I'm using some newer Qt stuff.
I'll change it so it compiles on Qt 5.12.

**Comment by g-fb** [comment]
Should work now.

**Comment by lgbaldoni** [comment]
Works for me, thanks!
