### ISSUE TITLE
some preset quality V/A settings + hardware decoding options

### ISSUE THREAD

**Issue by ahjolinna** [g-fb/haruna#24]
it would be nice to have some pre made video quality rendering settings and option to choose what Hw.decoding to use or at least what codecs are allowed (as some are just better on software)

if you don't know what settings would be good  for the preset I would copy the [mpc-qt](https://github.com/cmdrkotori/mpc-qt-origin) (seems to be a semi-dead project) that copy from [bomi ](https://github.com/xylosper/bomi/)(that is really dead project) ...sigh... to great Qt based mpv players that have died...sigh

**Comment by soredake** [comment]
Would be nice to have preset with these settings(i use this):
```
profile=gpu-hq
cscale=ewa_lanczossharp
scale=ewa_lanczossharp
```

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself, in a few days/weeks, if not done yet.

**Comment by ahjolinna** [comment]
> Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
> Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
> I'll move it myself, in a few days/weeks, if not done yet.

oh, CONGRATS!! if you haven't done the bug/feature request move yet I will do it probably tomorrow

**Comment by ahjolinna** [comment]
I moved it to bugs.kde.org
