### ISSUE TITLE
Cant customise mouse scroll actions

### ISSUE THREAD

**Issue by lgbaldoni** [g-fb/haruna#26]
Whatever I set is seemingly being ignored.

**Comment by g-fb** [comment]
Fixed 697b15e7bfde5df4f24847a5bdecbf8824dd7620

**Comment by lgbaldoni** [comment]
Applied that patch to 0.4.1, but while before the default action was being performed instead of the one I had chosen, now the scrollwheel is being ignored altogether.

(using scrollup/scrolldown for seekForwardMediumAction and seekBackwardMediumAction respectively)

**Comment by g-fb** [comment]
It works fine for me. Try to to set them to some other action and then set them back.

**Comment by lgbaldoni** [comment]
No change. I tried it however in a VM using Qt 5.15.2 and it worked.

With Qt 5.12.7 I also see various instances of this on console:
`qrc:/qml/Settings/Mouse.qml:50:17: Unable to assign [undefined] to QString`

**Comment by g-fb** [comment]
Are you sure you applied the patch?
I tried it on Leap with Qt 5.12.7 and it works.

**Comment by lgbaldoni** [comment]
It's strange. I tried the patched 0.4.1 in a Leap 15.2 VM and everything worked, but on my normal machine the problem still persists even after multiple reinstallations.

Could there be leftover config files besides haruna.conf ?

**Comment by g-fb** [comment]
It's not a config issue.
I get the same `qrc:/qml/Settings/Mouse.qml:50:17: Unable to assign [undefined] to QString` when running 0.4.1 without the patch.
But after applying the patch all is fine.

How are you building and running it?

**Comment by lgbaldoni** [comment]
0.4.2 works for me.

> How are you building and running it?

I created a rpm package on OBS. Speaking of which, do you think the application is now mature enough to be submitted for distro inclusion?

**Comment by g-fb** [comment]
> Speaking of which, do you think the application is now mature enough to be submitted for distro inclusion?

Not yet, there are still a lot of things that need to be fixed/improved, biggest problem is theming on non Plasma DEs.

**Comment by lgbaldoni** [comment]
> Not yet, there are still a lot of things that need to be fixed/improved, biggest problem is theming on non Plasma DEs.

Thanks. Please do let me know when you think that might be the case.

I guess this can be closed.
