### ISSUE TITLE
Option to control pulseaudio volume instead of softvol

### ISSUE THREAD

**Issue by soredake** [g-fb/haruna#27]
https://github.com/mpv-player/mpv/wiki/FAQ#I_want_the_old_PulseAudio_volume_control_back_on_Linux

**Comment by dpalacio** [comment]
I second this but I'll add some thougths. 

Doing this allows for better integration with the modern Linux desktop. While mpv behaves just as Haruna does, VLC, on the other hand, is integrated with the Pulseaudio volume control.

There are questions one has to ask. What is the use case of Haruna? Do you expect your target audience to use more than one instance at once? Would the final user benefit from having less sliders or controls to manage?

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself, in a few days/weeks, if not done yet.

**Comment by g-fb** [comment]
https://bugs.kde.org/show_bug.cgi?id=436883
