### ISSUE TITLE
[Feature request]: switch to force single instance

### ISSUE THREAD

**Issue by lgbaldoni** [g-fb/haruna#29]
of the application. Do you see it feasible?

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself, in a few days/weeks, if not done yet.
