### ISSUE TITLE
[Feature Request] Add ability to specify additional mpv options

### ISSUE THREAD

**Issue by IevgenSobko** [g-fb/haruna#32]
Is it possible to have some configuration to specify mpv additional options as Celluloid does?
That way users will be able to specify their own hardware encoding.
For instance, I would like to specify `--hwdec=vaapi` or `--hwdec=auto-safe` to force Intel hardware decoding. This works great for Celluloid and unloads my CPU.
But Haruna's automatic selection doesn't work for me like specified in https://github.com/g-fb/haruna/issues/30 and I need an alternative way to enable hardware acceleration.

**Comment by JJRcop** [comment]
This would even be fine as a config file entry for the moment without any UI, the UI could be added later.

**Comment by g-fb** [comment]
Added hardware decoding selection 62dfb39af02fceaa2ccabb0d4c060aa23eeb39ec

> Is it possible to have some configuration to specify mpv additional options as Celluloid does?

> This would even be fine as a config file entry for the moment without any UI, the UI could be added later.

No, as in I don't want to do it that way.

Anyway, you can try it by installing the beta, or compiling yourself.
```
flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta com.georgefb.haruna
flatpak run --branch=beta com.georgefb.haruna
```

**Comment by JJRcop** [comment]
If you don't wish to expose MPV options directly, what kind of options did you have in mind to expose in the UI?

**Comment by g-fb** [comment]
I do plan to add support for custom properties just not through config files.
