### ISSUE TITLE
Fullscreen broken since 0.5.0 release

### ISSUE THREAD

**Issue by abrasion66** [g-fb/haruna#33]
Since 0.5.0 i have that error when i try to go fullscreen :
qrc:/qml/MpvVideo.qml:282: Error: Cannot assign to non-existent property "state"

(i'm on ArchLinux uptodate)

**Comment by g-fb** [comment]
The package you installed is probably built from master,
which is not supposed to be packaged, not when there are tags available.

**Comment by abrasion66** [comment]
src/qml/MpvVideo.qml

282 -  settingsEditor.visible = "hidden"
     282 + "settingsEditor.visible = false

that work again for me

**Comment by g-fb** [comment]
What I said above still applies.

**Comment by abrasion66** [comment]
Sorry i'm noob with all that, so if i want to compile haruna i need to use 0.5.0 tags branch am i right ? (i'm just trying to learn)
I really like using haruna, it's simple and i do not want to see it over stuffed like smplayer is. So far haruna is really good, the playlist is, the option to skip chapter is great to skip openings on series/animes

**Comment by g-fb** [comment]
Yes. Not that the tags wont have bugs, but the master is more prone to things not working.

> over stuffed like smplayer

It will definitely get more settings/features.

**Comment by abrasion66** [comment]
Got it, thx for all
