### ISSUE TITLE
[Feature Request] docked playlist button

### ISSUE THREAD

**Issue by mhasadi78** [g-fb/haruna#34]
Hi, and thank you for this great work.
I would like to see an option to disable this mouse hover playlist. It is a bit annoying because of its size and it covers a lot of content on screen. An it would be even better if there was a button to click on it and toggle the docked playlist in relatively smaller form factor.

![Screenshot_20210119_103328](https://user-images.githubusercontent.com/41830018/104999234-c63a0f80-5a41-11eb-8df1-7a91e23803f5.png)
  And there is this happening when it shows playlist. The vertical lines are a little distorted.

AGAIN; thank you for this great project. Glad to see it grow.

System Information:

> Operating System: Arch Linux
> KDE Plasma Version: 5.20.5
> KDE Frameworks Version: 5.78.0
> Qt Version: 5.15.2
> Kernel Version: 5.10.7-arch1-1

**Comment by g-fb** [comment]
> option to disable this mouse hover playlist

Settings > Playlist > Toggle with mouse
You can toggle it with the "P" key.

Regarding the unaligned lines, it might be the font. What font are you using?

**Comment by mhasadi78** [comment]
Thank you, it has solved most of it.
About unaligned lines, you were right, I changed the font to default and rebooted my machine and it looks normal now.

But my main suggestion still remains, option to dock playlist would make some decent improvement in terms of UX. What I mean by docking is that the playlist would stay in the right/left side and the video itself become smaller. Therefor the video content won't covered by playlist. Something like Firefox sidebar.
And in my opinion it would look better if it was in a smaller form factor. But that's my personal preference and in the end, it's your call.

![Firefox Sidebar](https://user-images.githubusercontent.com/41830018/105065186-d5957900-5a92-11eb-91cc-d9ed51c8e3f5.png)

**Comment by g-fb** [comment]
> the playlist would stay in the right/left side and the video itself become smaller

Don't know about this one. That's one thing I disliked about existing players.
I'll look into it though, if it's an easy change I'll add an option.

**Comment by g-fb** [comment]
Also, what's the font you used?

**Comment by mhasadi78** [comment]
Hi, Sorry for late reply.
It was a handmade font that I made myself. So it's not likely any other user would use it. I say it's waste of time focusing on that part. Especially that I had digged into fontconfig config files of my system lately. But if you insist, It was a combination of Fira Sans and a Persian font named Sahel. The problem was on my end clearly.

**Comment by Josh68** [comment]
Adding another thanks for this simple player, @g-fb . I only figured out how to turn off the auto-opening playlist by reading your response to this issue. I like that I can toggle it with a keystroke, and also kind of like the overlay vs docked style. But it would be helpful to provide some documentation or list of shortcuts. Sorry if that already exists and I'm missing it.

**Comment by g-fb** [comment]
> But it would be helpful to provide some documentation or list of shortcuts

Menu > Settings > Configure Keyboard Shortcuts.
Toolbar > Configure > Shortcuts

You can see and edit all shortcuts.

**Comment by Josh68** [comment]
Thanks!

**Comment by g-fb** [comment]
@mhasadi78 There's an option to disable the playlist going on top of the video. Settings > Playlist > Overlay video
And also a more compact playlist style. Settings > Playlist > Playlist style > Compact
When "Toggle with mouse" option is disabled a button  to toggle the playlist will be shown in the footer, left or right depending on the playlist position.

You can try it by installing the beta
```
flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta com.georgefb.haruna
flatpak run --branch=beta com.georgefb.haruna
```
Or compiling it yourself.
