### ISSUE TITLE
Submitting the project in KDE

### ISSUE THREAD

**Issue by Mazino-Urek** [g-fb/haruna#35]
I have recently come across this video player. This project already uses KDE dependencies and KDE application suit is missing a video player with active development.
Elisa was also an standalone project, now it has received tremendous development and is a great product now.
Kindly give it a thought. God speed!

**Comment by g-fb** [comment]
I've thought about it, but they already have 2 new qml projects 
https://invent.kde.org/maui/cinema
https://invent.kde.org/cblack/kine
Plus the 3 older ones.

**Comment by Mazino-Urek** [comment]
Can I tag Nate Graham? Maybe he has some opinion?

**Comment by g-fb** [comment]
There are other reasons I haven't done it, besides the existing projects.

**Comment by Mazino-Urek** [comment]
Got it. Thanks for the time. 
Good luck with the project!
