### ISSUE TITLE
feature request: ability to sort playlist by date

### ISSUE THREAD

**Issue by tomtomme** [g-fb/haruna#37]
Would be nice if the playlist would respect the current sorting used in the filemanager from which the file was opened.
Or if I could control sorting from within the player

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself, in a few days/weeks, if not done yet.

**Comment by g-fb** [comment]
https://invent.kde.org/multimedia/haruna/-/issues/2
