### ISSUE TITLE
feature request: delete file with shortcut or with contextmenu from playlist

### ISSUE THREAD

**Issue by tomtomme** [g-fb/haruna#38]
would also be nice to be able to delete a file with a shortcut or with a contextmenu from the playlist. switching to the filemanager is so anoying :D
great player you have here, by the way. the best mpv frontend out there.

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself, in a few days/weeks, if not done yet.

**Comment by g-fb** [comment]
https://invent.kde.org/multimedia/haruna/-/issues/3
