### ISSUE TITLE
Latest build not working on archlinux

### ISSUE THREAD

**Issue by ElishaDaugherty** [g-fb/haruna#39]
Hi,

I don't know if you are the maintainer of the package in aur, but I'm using it to build the haruna in archlinux (since this is the easiest way to do it).
It is finished without any error, but when I open the program, I get this error:

```
Cyclic dependency detected between "file:///usr/lib/qt/qml/org/kde/kirigami.2/styles/org.kde.desktop.plasma/Units.qml" and "file:///usr/lib/qt/qml/org/kde/kirigami.2/styles/org.kde.desktop.plasma/Units.qml"
QQmlApplicationEngine failed to load component
qrc:/qml/main.qml:88:5: Type PlayList unavailable
qrc:/qml/PlayList.qml:50:9: Type PlayListItemWithThumbnail unavailable
qrc:/qml/PlayListItemWithThumbnail.qml:14:1: module "Haruna.Components" is not installed
```

Maybe it's a packaging error? Does it look like something is missing? Maybe an additional dependency?

Thanks!

https://aur.archlinux.org/packages/haruna-git/

**Comment by g-fb** [comment]
> I don't know if you are the maintainer of the package in aur

No

If you want to build it for daily use see my replies here #33
