### ISSUE TITLE
Feature Request: Multimedia control integration with desktop

### ISSUE THREAD

**Issue by dpalacio** [g-fb/haruna#46]
I don't know what the current tech it is today, but the last I heard of was called MPRIS. It allows you to control a multimedia instance from outside of its application. For example, a Plasma panel or the locked screen allow you to pause the video. I know mpv doesn't have this, but VLC does, and it is a nice thing to have.

**Comment by g-fb** [comment]
Added.

You can test it on the [beta version](https://github.com/g-fb/haruna#beta).
