### ISSUE TITLE
Feature request: compatability with mpv commandline parameters

### ISSUE THREAD

**Issue by soredake** [g-fb/haruna#47]
[Syncplay](https://github.com/Syncplay/syncplay) for example starts mpv with this parameters ` --force-window=yes --idle=yes --hr-seek=always --keep-open=always --input-terminal=no --term-playing-msg=<SyncplayUpdateFile> ANS_filename=${filename} ANS_length=${=duration:${=length:0}} ANS_path=${path} </SyncplayUpdateFile> --keep-open-pause=yes --script=/usr/lib/syncplay/syncplay/resources/syncplayintf.lua --input-ipc-server=/tmp/mpv20890300659741 --input-terminal=no --terminal=no`

I want to ditch mpv and replace it with haruna, but want to keep compatibility with syncplay.

**Comment by g-fb** [comment]
I want to add a way for users to add their own properties, which will be loaded at start up.
Which is pretty much the same as what you ask for.

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself, in a few days/weeks, if not done yet.
