### ISSUE TITLE
High cpu usage v0.1.4 

### ISSUE THREAD

**Issue by danrobi11** [g-fb/haruna#5]
Hello Are you maintaining the flatpak version?
High cpu usage here.
Processor: AMD A4-3300M APU with Radeon(tm) HD Graphics
Memory: 3497MB (2046MB used)
Machine Type: Notebook
Operating System: Debian GNU/Linux 10 (buster)

**Comment by g-fb** [comment]
What resolution was the video? How is playback with other players?
If it's the same then maybe your CPU needs that usage.
I have a Ryzen 2600 and playing a 2160p video used ~20%, 1440p ~10% CPU and I got the same with mpv.

**Comment by danrobi11** [comment]
Hello
Yep, the issue was the reso. As haruna probly pulling best reso, the reso must be like 4k or something. I cant tell theres no reso option nor details in haruna.
I've tested an url vid that I know for it to be 480p and haruna was using normal cpu usage. 
So ya, we def need that reso option. (I know , I saw that was on roadmap, thx )

**Comment by g-fb** [comment]
I released a new version with the option for selecting a video format. 
If you're using the flatpak version run `flatpak update` and you should get the update.

**Comment by danrobi11** [comment]
Thank you very much!
