### ISSUE TITLE
[Feature request] Ability to amplify volume (over 100% volume)

### ISSUE THREAD

**Issue by ShrirajHegde** [g-fb/haruna#50]
It would be great if audio settings allowed setting `--volume-max` to allow over 100% volume for files with low volume

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself, in a few days/weeks, if not done yet.

**Comment by g-fb** [comment]
This will be possible once custom properties are implemented, hopefully next version 0.7.0.
