### ISSUE TITLE
[Feature Request] Ability to seek with mouse scroll

### ISSUE THREAD

**Issue by ShrirajHegde** [g-fb/haruna#51]
Ability to seek quickly with scroll with cursor on timeline.

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself, in a few days/weeks, if not done yet.
