### ISSUE TITLE
Menu bar not scaling when using Plasma's 'global scale' feature

### ISSUE THREAD

**Issue by Baemir** [g-fb/haruna#55]
[Here's a picture of the menu bar at the default 100% scale](https://i.imgur.com/Z9jgUT5.png)
[Here's a picture of the menu bar at 175% scaling](https://i.imgur.com/dxt2opb.png)

As you can see, the text scales, but the background doesn't, with quite ugly results. Even at 125% scale it's very noticeable. Nice app btw, I like it. :+1:

**Comment by g-fb** [comment]
Did you restart after changing the scale?

**Comment by Baemir** [comment]
> Did you restart after changing the scale?

Yes, of course.

**Comment by Baemir** [comment]
> Did you restart after changing the scale?

Yes, of course.

**Comment by g-fb** [comment]
Works for me on openSUSE TW.

What distro are you using?

Also, how did you install?

**Comment by Baemir** [comment]
KDE Neon. I downloaded it from Discover, I think it was a normal source package (as opposed to flatpak etc.) But I'll check and edit this comment tomorrow

**Comment by Baemir** [comment]
Nvm, it's a flatpak.

**Comment by g-fb** [comment]
I'm using the flatpak version and 131,25% scaling and have no problems.
Which edition of Neon are you using?

**Comment by g-fb** [comment]
Tested on the user edition with 125% scaling and can't reproduce.
