### ISSUE TITLE
Need proxy option

### ISSUE THREAD

**Issue by danrobi11** [g-fb/haruna#6]
Hello 
Proxy option / http, socks5

**Comment by g-fb** [comment]
Please explain the use case.
I never used proxies and I can't add a feature if I don't now how it's supposed to work.

**Comment by danrobi11** [comment]
most commun used case is to be run over TOR= SOCKS5://127.0.0.1:9050
Otherwise for other network, http/https= 127.0.0.1:xxxx or localhost:xxxx

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself, in a few days/weeks, if not done yet.

**Comment by g-fb** [comment]
https://bugs.kde.org/show_bug.cgi?id=436882
