### ISSUE TITLE
[Feature request]: Localization

### ISSUE THREAD

**Issue by lgbaldoni** [g-fb/haruna#60]
The app appears to be mature enough for that.
I volunteer for the Italian translation.

**Comment by IsildurSamar** [comment]
I volunteer for Polish translation.

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.

The translations will be done through their system. Not sure how that works yet.

**Comment by g-fb** [comment]
I opened an issue [here](https://invent.kde.org/multimedia/haruna/-/issues/11), I'll post there once I figure things out.
