### ISSUE TITLE
High consumption of RAM memory

### ISSUE THREAD

**Issue by ElishaDaugherty** [g-fb/haruna#61]
Someone posted your work on reddit and I decided to test it on my kde plasma. I loved the interface and the options that are already there, but then I realized that the RAM usage is way above what I expected for a video player.

Here is a small comparison of memory usage with three popular players. All are with a video of about 430 MB open.

![ksnip_tmp_ELbbhn](https://user-images.githubusercontent.com/77898421/113300695-90809500-92d4-11eb-9627-1d8d1e1ca38f.png)

haruna is consuming much more than smplayer, which also uses mpv as backend

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself, in a few days/weeks, if not done yet.

**Comment by g-fb** [comment]
https://bugs.kde.org/show_bug.cgi?id=436885
