### ISSUE TITLE
casting support

### ISSUE THREAD

**Issue by kinghat** [g-fb/haruna#62]
looking for the ability, outside of VLC, to cast videos from a player to chromecast. there are other casting protocols like airplay but for me its chromecast. discussion from here: https://www.reddit.com/r/linux/comments/mh5cua/haruna_video_player_060_released/gsya3pc/?context=3

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself, in a few days/weeks, if not done yet.

**Comment by kinghat** [comment]
> Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
> Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
> I'll move it myself, in a few days/weeks, if not done yet.

you want this filed as a bug rather than an issue on the new repo?

**Comment by g-fb** [comment]
Yes, kde uses the repo issues for developer tasks.

**Comment by g-fb** [comment]
https://bugs.kde.org/show_bug.cgi?id=436744
