### ISSUE TITLE
[Feature request]: Change subtitle color & Sharpen video.

### ISSUE THREAD

**Issue by IsildurSamar** [g-fb/haruna#65]
Is it possible to change subtitle color? Can't find this feature.
Also sharpen would be very helpful. 
(You are on the way to make best Linux Video player. Thank you!)

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself, in a few days/weeks, if not done yet.

**Comment by g-fb** [comment]
https://bugs.kde.org/show_bug.cgi?id=436888
