### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by omid455** [g-fb/haruna#71]
Latest flatpack version is missing the control icons. I have the same issue across multiple Linux installations. screenshot attached.
![image](https://user-images.githubusercontent.com/64040596/115898044-c7764080-a465-11eb-8f4d-b90f70cf0cd6.png)

**Comment by g-fb** [comment]
Make sure you check `Use Breeze icon theme` in Configure > General and restart.

**Comment by omid455** [comment]
> Make sure you check `Use Breeze icon theme` in Configure > General and restart.

Thanks! It is ok now. By the way, great video player. I love it.
