### ISSUE TITLE
Missing playback control icons

### ISSUE THREAD

**Issue by CarnageDevs** [g-fb/haruna#72]
On the latest Flatpak version, the playback controls don't show for me on KDE when the system is using a non-standard icon theme (aka an icon theme outside of Breeze). Tested on Fedora 34 KDE and a fresh install of OpenSUSE Tumbleweed, icons only show when the system is using Breeze as its icon theme. I've tried multiple icon themes and _every_ icon theme outside of Breeze results in this issue.

![](https://i.imgur.com/QIkbvgO.png)

I've enabled **"Use Breeze icon theme"** and restarted both the app and my PC to no avail. Running the program via the terminal using `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=haruna --file-forwarding com.georgefb.haruna @@u %u @@` results in the following output (same output with/without **"Use Breeze icon theme"** enabled):
```
Icon theme "Tela-dark" not found.
Icon theme "Tela-dark" not found.
```

**Comment by g-fb** [comment]
Should be fixed now.
You can test it in the beta https://github.com/g-fb/haruna#beta
