### ISSUE TITLE
Where are AppImage?

### ISSUE THREAD

**Issue by gusarg81** [g-fb/haruna#73]
Hi,

The Readme indicates that are in Releases but I don't see any AppImage there.

PD: I hope that this issues does not end without replies like the rest of the created issues.

**Comment by ShrirajHegde** [comment]
appimage in release workflow was created and merged after the last release,
use this as of now, next releases will have appimage.

**Comment by ShrirajHegde** [comment]
or you can find the continuously built appimage in actions.

**Comment by ShrirajHegde** [comment]
@gusarg81 check now

**Comment by gusarg81** [comment]
Good, downloaded and installed. Thanks.
