### ISSUE TITLE
Add a setting to disable opening of last viewed video on startup?

### ISSUE THREAD

**Issue by JustAHumanBean** [g-fb/haruna#74]
Hi, can you add a setting to disable opening of last viewed video on startup?

Thanks.

**Comment by JustAHumanBean** [comment]
Workaround for now:
sudo chattr +i ~/.var/app/com.georgefb.haruna/config/georgefb/haruna.conf

**Comment by g-fb** [comment]
Haruna has joined KDE and has moved to https://invent.kde.org/multimedia/haruna.
Consider moving this to [bugs.kde.org](https://bugs.kde.org/enter_bug.cgi?product=Haruna&component=generic), to get notified about progress.
I'll move it myself in a few days/weeks, if not done yet.

**Comment by g-fb** [comment]
https://bugs.kde.org/show_bug.cgi?id=436887
