### ISSUE TITLE
[Bug] Seeking with Arrow Keys not working

### ISSUE THREAD

**Issue by ghost** [g-fb/haruna#9]
I have keybindings for the various seeking options set to the arrows keys as shown in the screenshot. In the video they don't work. MPV still works fine in this regard.
![Screenshot_20200729_132409](https://user-images.githubusercontent.com/41188546/88794574-f396b680-d19e-11ea-9995-42d51ee39ddf.png)

**Comment by g-fb** [comment]
~~This is weird. They work for me.~~
~~Can you rename the config file \~/.var/app/com.georgefb.haruna/config/georgefb/haruna.conf to something else and test with defaults?~~
~~Did they work before updating?~~

It's the language. Just tried with German and they stopped working.

**Comment by g-fb** [comment]
Please try the beta
```
flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta com.georgefb.haruna
flatpak run --branch=beta com.georgefb.haruna
```

**Comment by ghost** [comment]
I have tested it and it works fine. I will close the issue when this change hits the stable release.

**Comment by g-fb** [comment]
I updated the stable version.

**Comment by ghost** [comment]
Thanks! It works fine!
